module Async
  class << self
    def stack_increase_size(ins)
      STACK_INCREASE_MAP[ins[0]] ||
        STACK_INCREASE_CALC_MAP[ins[0]].call(ins) ||
        raise(ArgumentError, "unknown instruction: #{ins}")
    end
  end

  STACK_INCREASE_CALC_MAP = {
    concatstrings: -> ins { 1 - ins[1] },
    newarray: -> ins { 1 - ins[1] },
    newhash: -> ins { 1 - ins[1] },
    invokeblock: -> ins { 1 - ins[1][:orig_argc] },
    toregexp: -> ins { 1 - ins[2] },
    adjuststack: -> ins { -ins[1] },
    dupn: -> ins { ins[1] },
    expandarray: -> ins { ins[1] - 1 + (ins[2] & 1 > 0 ? 1 : 0) },
    opt_send_without_block: -> ins { -ins[1][:orig_argc] },
    invokesuper: -> ins { -(ins[1][:orig_argc] + (ins[1][:flag] & 2 > 0 ? 1 : 0)) },
    send: -> ins { -(ins[1][:orig_argc] + (ins[1][:flag] & 2 > 0 ? 1 : 0)) },
  }

  STACK_INCREASE_MAP = {
    defined: 0,
    getconstant: 0,
    jump: 0,
    leave: -1, ###
    nop: 0,
    opt_aref_with: 0,
    opt_call_c_function: 0,
    opt_empty_p: 0,
    opt_length: 0,
    opt_not: 0,
    opt_regexpmatch1: 0,
    opt_size: 0,
    opt_succ: 0,
    reput: 0,
    reverse: 0,
    setinlinecache: 0,
    setn: 0,
    splatarray: 0,
    swap: 0,
    throw: 0,
    tostring: 0,
    trace: 0,
    answer: 1,
    bitblt: 1,
    checkkeyword: 1,
    dup: 1,
    duparray: 1,
    getclassvariable: 1,
    getglobal: 1,
    getinlinecache: 1,
    getinstancevariable: 1,
    getlocal: 1,
    getlocal_OP__WC__0: 1,
    getlocal_OP__WC__1: 1,
    getspecial: 1,
    once: 1,
    opt_str_freeze: 1,
    putiseq: 1,
    putnil: 1,
    putobject: 1,
    putobject_OP_INT2FIX_O_0_C_: 1,
    putobject_OP_INT2FIX_O_1_C_: 1,
    putself: 1,
    putspecialobject: 1,
    putstring: 1,
    topn: 1,
    branchif: -1,
    branchnil: -1,
    branchunless: -1,
    checkmatch: -1,
    concatarray: -1,
    defineclass: -1,
    newrange: -1,
    opt_aref: -1,
    opt_aset_with: -1,
    opt_case_dispatch: -1,
    opt_div: -1,
    opt_eq: -1,
    opt_ge: -1,
    opt_gt: -1,
    opt_le: -1,
    opt_lt: -1,
    opt_ltlt: -1,
    opt_minus: -1,
    opt_mod: -1,
    opt_mult: -1,
    opt_neq: -1,
    opt_plus: -1,
    opt_regexpmatch2: -1,
    pop: -1,
    setclassvariable: -1,
    setglobal: -1,
    setinstancevariable: -1,
    setlocal: -1,
    setlocal_OP__WC__0: -1,
    setlocal_OP__WC__1: -1,
    setspecial: -1,
    opt_aset: -2,
    setconstant: -2,
  }
end
